name: Build and Publish Plugin

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: false

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build Plugin
        run: ./gradlew buildPlugin

      - name: Publish Plugin
        run: ./gradlew publishPlugin
        env:
          INTELLIJ_PUBLISH_TOKEN: ${{ secrets.INTELLIJ_PUBLISH_TOKEN }}
